### ISSUE TITLE
`getDistributors` or similar new method should return friendly names

### ISSUE THREAD

**Issue by karmanyaahm** [UnifiedPush/android-connector#35]
Like the application names `registerAppWithDialog` uses.

https://github.com/UnifiedPush/android-connector/blob/234eaf55a500e63bca1daaa54b84c66f46f83a0b/connector/src/main/java/org/unifiedpush/android/connector/Registration.kt#L69-L85

**Comment by p1gp1g** [comment]
The problem is, unlike the package names, the application names are not unique. It would cause issues with `saveDistributor`.

They are still some solutions :
* We can do `getAppName(context: Context, package: String)` for convenience. This function is not really related to UP.
* Another solution would be to create a Distributor object, containing the app name and the package name, returned by `getDistributor`. This solution would be an incompatible change.
* Or we can do a `getDistributorObject`, but it can make things more confused by increasing the number of functions

**Comment by karmanyaahm** [comment]
Hmm... That's a good point. I only need this for flutter over method channels, so I'll move this issue to the flutter lib and will solve it in the method channels interface.

**Comment by karmanyaahm** [comment]
Additionally, objects don't work with method channels (afaik?) so using the last 2 options will only complicate things further in there.

**Comment by p1gp1g** [comment]
A `getAppName` for flutter-connector makes sense since it is multi platform. At least maps are usable on channels
