### ISSUE TITLE
Make dialog strings translateable

### ISSUE THREAD

**Issue by connyduck** [UnifiedPush/android-connector#57]
Currently the text displayed to users in dialogs is hardcoded. It would be cool if they were Android string resources so client apps can override them and/or provide additional translations. Ideally the connector already comes with translations in common languages.

**Comment by p1gp1g** [comment]
Dialog strings can be overridden with the optional param `registrationDialogContent`.

Check the documentation to use it (java or kotlin) : https://unifiedpush.org/developers/android/

Params are here : https://github.com/UnifiedPush/android-connector/blob/main/connector/src/main/java/org/unifiedpush/android/connector/RegistrationDialogContent.kt

I'm closing this issue since the text can be overridden and translated :)

**Comment by p1gp1g** [comment]
Note that suggestions to improve this are welcome :)
